trigger:
  branches:
    include:
    - master
    - refs/tags/*

jobs:
- job: build
  pool:
    vmImage: 'windows-latest'

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

- job: releaseNuget
  condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
  dependsOn: build
  pool:
    vmImage: 'windows-latest'

  variables:
    buildConfiguration: 'Release'
    projectsToPack: 'Infrastructure.Option/Infrastructure.Option.csproj'

  steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack'
    inputs:
      command: pack
      packagesToPack: '$(projectsToPack)'
      packDirectory: '$(Build.ArtifactStagingDirectory)/packages/releases'

  - task: NuGetCommand@2
    displayName: 'nuget push'
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/packages/releases/*.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'NuGet'
      nobuild: true
